### ISSUE TITLE
Support keywords (like returns, example,etc)

### ISSUE THREAD

**Issue by somenxavier** [BurntSushi/pdoc#59]
Like [sphinx](http://sphinx-doc.org/ext/napoleon.html#module-sphinx.ext.napoleon), can you provide keywords like `returns` or `example` to document such things?

Thanks a lot,

**Comment by BurntSushi** [comment]
Absolutely not. The whole point of using Markdown was to encourage writing documentation using prose rather than be burdened with the mental overhead of remembering annotations.

(Not everyone agrees with this, and that's OK, but for better or worse, than is the trade off made by `pdoc`. See: https://github.com/BurntSushi/pdoc#motivation)

**Comment by somenxavier** [comment]
Ok. But how do you refer to a Class of your module? With a link?

**Comment by BurntSushi** [comment]
Yup. See the docs "Linking to other identifiers": http://pdoc.burntsushi.net/pdoc

**Comment by somenxavier** [comment]
Thanks for references. What about external references like python json module?

**Comment by BurntSushi** [comment]
@somenxavier Create a [hyperlink](https://docs.python.org/2.7/library/json.html#module-json).
